export class CityName {
    cities: string[] = [
            "Agareb",
            "Ajim",
            "Akouda",
            "Alaâ",
            "Amiret El Fhoul",
            "Amiret El Hojjaj",
            "Amiret Touazra",
            "Aousja",
            "Ariana",
            "Azmour",
            "Aïn Djeloula",
            "Aïn Draham",
            "Bargou",
            "Bekalta",
            "Bembla-Mnara",
            "Ben Arous",
            "Ben Gardane",
            "Benen Bodher",
            "Beni Hassen",
            "Beni Khedache",
            "Beni M'Tir",
            "Bir Ali Ben Khélifa",
            "Bir El Hafey",
            "Bir Lahmar",
            "Bir Mcherga",
            "Bizerte",
            "Borj El Amri",
            "Bou Arada",
            "Bou Argoub",
            "Bou Hajla",
            "Bou Merdes",
            "Bou Mhel el-Bassatine",
            "Bou Salem",
            "Bouficha",
            "Bouhjar",
            "Béja",
            "Béni Khalled",
            "Béni Khiar",
            "Carthage",
            "Cebalet",
            "Chebba",
            "Chebika",
            "Chenini Nahal",
            "Cherahil",
            "Chihia",
            "Chorbane",
            "Dahmani",
            "Dar Allouch",
            "Dar Chaabane",
            "Degache",
            "Dehiba",
            "Den Den",
            "Djebel Oust",
            "Djedeida",
            "Djemna",
            "Douar Hicher",
            "Douz",
            "Echrarda Echrarda</option>",
            "El Ain",
            "El Alia",
            "El Aroussa",
            "El Battan",
            "El Bradâa",
            "El Djem",
            "El Fahs",
            "El Golâa",
            "El Guettar",
            "El Hamma",
            "El Haouaria",
            "El Hencha",
            "El Krib",
            "El Ksar",
            "El Ksour",
            "El Masdour",
            "El Maâgoula",
            "El Maâmoura",
            "El Mida",
            "El Mourouj",
            "Enfidha",
            "Essouassi",
            "Ettadhamen-Mnihla",
            "Ezzahra",
            "Ezzouhour",
            "Fernana",
            "Foussana",
            "Fériana",
            "Gabès",
            "Gafsa",
            "Gaâfour",
            "Ghannouch",
            "Ghar al Milh",
            "Ghardimaou",
            "Ghenada",
            "Ghomrassen",
            "Ghraïba",
            "Goubellat",
            "Gremda",
            "Grombalia",
            "Haffouz",
            "Hajeb El Ayoun",
            "Hamet Jerid",
            "Hammam Chott",
            "Hammam Ghezèze",
            "Hammam Lif",
            "Hammam Sousse",
            "Hammamet",
            "Haïdra",
            "Hebira",
            "Hergla",
            "Houmt El Souk",
            "Jebiniana",
            "Jedelienne",
            "Jemmal",
            "Jendouba",
            "Jilma",
            "Jérissa",
            "Kairouan",
            "Kalaat es Senam",
            "Kalâa Kebira",
            "Kalâa Seghira",
            "Kalâat Khasba",
            "Kalâat el-Andalous",
            "Kasserine",
            "Kebili",
            "Kef",
            "Kelibia",
            "Kerkennah",
            "Kerker",
            "Kesra",
            "Khalidia",
            "Khniss",
            "Kondar",
            "Korba",
            "Korbous",
            "Ksar Hellal",
            "Ksibet El Mediouni",
            "Ksibet Thrayet",
            "Ksour Essef",
            "La Goulette",
            "La Marsa",
            "La Soukra",
            "Le Bardo",
            "Le Kram",
            "Lemta",
            "M'saken",
            "Magel Bel Abbès",
            "Mahares",
            "Mahdia",
            "Majaz al Bab",
            "Maktar",
            "Manouba",
            "Mareth",
            "Mateur",
            "Matmata",
            "Mdhila",
            "Medenine",
            "Meknassy",
            "Melloulèche",
            "Menzel Abderrahmane",
            "Menzel Bourguiba",
            "Menzel Bouzaiane",
            "Menzel Bouzelfa",
            "Menzel Chaker",
            "Menzel Ennour",
            "Menzel Farsi",
            "Menzel Hayet",
            "Menzel Horr",
            "Menzel Jemil",
            "Menzel Kamel",
            "Menzel Mehiri",
            "Menzel Salem",
            "Menzel Temime",
            "Messaadine",
            "Metline",
            "Mezzouna",
            "Midoun",
            "Mohamedia-Fouchana",
            "Moknine",
            "Monastir",
            "Mornag",
            "Mornaguia",
            "Moularès",
            "Mégrine",
            "Métlaoui",
            "Métouia",
            "Nabeul",
            "Nadhour",
            "Nafta",
            "Nasrallah",
            "Nebeur",
            "Nefza",
            "Nouvelle Matmata",
            "Oudhref",
            "Oued Ellil",
            "Oued Melliz",
            "Ouerdanin",
            "Oueslatia",
            "Ouled Chamekh",
            "Ouled Haffouz",
            "Radès",
            "Raf Raf",
            "Raoued",
            "Ras Jebel",
            "Redeyef",
            "Regueb",
            "Rejiche",
            "Remada",
            "Rouhia",
            "Sahline Moôtmar",
            "Sakiet Eddaïer",
            "Sakiet Ezzit",
            "Sakiet Sidi Youssef",
            "Sayada",
            "Sbeitla",
            "Sbiba",
            "Sbikha",
            "Sejnane",
            "Sened",
            "Sers",
            "Sfax",
            "Sidi Ali Ben Aoun",
            "Sidi Alouane",
            "Sidi Ameur",
            "Sidi Bennour",
            "Sidi Bou Ali",
            "Sidi Bou Rouis",
            "Sidi Bou Said",
            "Sidi Bouzid",
            "Sidi El Hani",
            "Sidi Hassine",
            "Sidi Thabet",
            "Siliana",
            "Skhira",
            "Soliman",
            "Somâa",
            "Souk Lahad",
            "Sousse",
            "Tabarka",
            "Tajerouine",
            "Takelsa",
            "Tamerza",
            "Tataouine",
            "Tazerka",
            "Tebourba",
            "Testour",
            "Thala",
            "Thyna",
            "Thélepte",
            "Tinja",
            "Touiref",
            "Touza",
            "Tozeur",
            "Tunis",
            "Téboulba",
            "Téboursouk",
            "Zaghouan",
            "Zahret Medien",
            "Zaouiet Djedidi",
            "Zaouiet Kontoch",
            "Zaouiet Sousse",
            "Zarat",
            "Zarzis",
            "Zriba",
            "Zéramdine"
        ]
}